export type CardIconName =
    | "Airplane"
    | "Alarm Clock"
    | "Alexa"
    | "Analytics Interface"
    | "Apple"
    | "Applications"
    | "Architect"
    | "Assembly Line"
    | "Astronaut"
    | "Athlete Female"
    | "Athlete Male"
    | "Backpack"
    | "Bandwidth"
    | "Bar Chart 1"
    | "Bar Chart 2"
    | "Bar Code"
    | "Battery"
    | "Bicycle"
    | "Blockchain"
    | "Blog"
    | "Book"
    | "Book Open"
    | "Bookmark"
    | "Books"
    | "Briefcase"
    | "Browser"
    | "Browser Apps"
    | "Browser Click"
    | "Bucket"
    | "Bug"
    | "Bulldozer"
    | "Bus 1"
    | "Bus 2"
    | "Caduceus"
    | "Cafe"
    | "Calculator"
    | "Calendar"
    | "Camera"
    | "Camera Lense"
    | "Capture Image"
    | "Car Front View"
    | "Car Side View"
    | "Car Top View"
    | "Cash"
    | "Castle"
    | "Certificate"
    | "Chat"
    | "Chat Conversation"
    | "Check List"
    | "Cityscape"
    | "Clipboard"
    | "Clock"
    | "Coffee Cup"
    | "Coffee Maker"
    | "Coin"
    | "Computer Chip"
    | "Computer User Female"
    | "Computer User Male"
    | "Control Tower"
    | "Controls"
    | "Crane"
    | "Credit Card Back"
    | "Credit Card Front"
    | "Cursor"
    | "DNA"
    | "Dashboard"
    | "Data"
    | "Data Lake"
    | "Data Warehouse"
    | "Database"
    | "Databases"
    | "Desk"
    | "Desk with Girl"
    | "Desktop"
    | "Desktop Apps"
    | "Desktop Click"
    | "Desktop Export"
    | "Desktop Import"
    | "Desktop Laptop"
    | "Desktop Mobile"
    | "Devices"
    | "Directory"
    | "Disease"
    | "Document"
    | "Documents"
    | "Documents Stacked"
    | "Dollar and Euro"
    | "Dollar and Pound"
    | "Dollar and Yen"
    | "Dollar & Euro"
    | "Dollar & Pound"
    | "Dollar & Yen"
    | "Dollar Sign"
    | "Dump Truck"
    | "Emoji 1"
    | "Emoji 2"
    | "Encrypt Chip"
    | "Envelope Closed"
    | "Envelope Open"
    | "Euro"
    | "Event Trigger"
    | "Facebook"
    | "Factory 1"
    | "Factory 2"
    | "Factory Worker"
    | "File"
    | "File Cabinet"
    | "Filter"
    | "Firewall"
    | "First Aid"
    | "Flag"
    | "Flow Chart 1"
    | "Flow Chart 2"
    | "Folder"
    | "Food"
    | "Forklift"
    | "Free 1"
    | "Free 2"
    | "Fully Managed"
    | "Game Console"
    | "Game Control"
    | "Gamer Female"
    | "Gamer Male"
    | "Gauge"
    | "Gavel"
    | "Group 1"
    | "Group 2"
    | "Hard Drive"
    | "Headset"
    | "Helicopter"
    | "Hospital"
    | "Hot Air Balloon"
    | "Hourglass"
    | "House"
    | "Identification"
    | "Image"
    | "Infrastructure"
    | "Infrastructure Statistical"
    | "Instagram"
    | "IoT"
    | "Key"
    | "Lab Technician"
    | "Laptop"
    | "Laptop Apps"
    | "Laptop Click"
    | "Laptop Cluster"
    | "Laptop Export"
    | "Laptop Import"
    | "Laptop Mobile"
    | "Leader"
    | "Line Chart"
    | "Line Graph"
    | "Link"
    | "Lock"
    | "MRI"
    | "Machine Learning"
    | "Machine Learning Models"
    | "Mailbox"
    | "Malware"
    | "Marketplace Cart"
    | "Mechanical Arm 1"
    | "Mechanical Arm 2"
    | "Microphone"
    | "Microscope"
    | "Mobile Apps"
    | "Mobile Chat"
    | "Mobile Export"
    | "Mobile Import"
    | "Mobile Map"
    | "Mobile Phone"
    | "Mobile Tap"
    | "Mobile User Profile"
    | "Mobile Website"
    | "Mouse"
    | "Music Notes"
    | "Newspaper"
    | "Notebook"
    | "Oil Drill"
    | "Oil Truck"
    | "On-Premises Server"
    | "Open Lock"
    | "Package Open"
    | "Paper Clip"
    | "Pencil Holder"
    | "Person"
    | "Person Assistant"
    | "Person Female 1"
    | "Person Female 2"
    | "Person Female 3"
    | "Person Male 1"
    | "Person Male 2"
    | "Person Male 3"
    | "Person Male 4"
    | "Person with Headphones"
    | "Phone"
    | "Pickaxe"
    | "Pie Chart"
    | "Piggy Bank"
    | "Pills"
    | "Play Button"
    | "Plug"
    | "Pound"
    | "Ribbon"
    | "Rocket"
    | "Rocket Ship"
    | "Satellite"
    | "Scale"
    | "Scale Down"
    | "Scale Up"
    | "Scanning Data"
    | "School"
    | "School Bus"
    | "Security Alert"
    | "Security Camera"
    | "Server"
    | "Settings"
    | "Shield"
    | "Ship"
    | "Slide Show"
    | "Sound Waves"
    | "Speaker"
    | "Spreadsheet"
    | "Stack Instance"
    | "Stopwatch"
    | "Streaming"
    | "Student Female"
    | "Student Male"
    | "Suitcase"
    | "T-shirt"
    | "TV Console"
    | "Tablet"
    | "Tablet Apps"
    | "Tablet Export"
    | "Tablet Import"
    | "Tablet Mobile"
    | "Tablet Tap"
    | "Tag"
    | "Target"
    | "Tennis Player"
    | "Test Tube and Beaker 1"
    | "Test Tube and Beaker 2"
    | "Test Tube & Beaker 1"
    | "Test Tube & Beaker 2"
    | "Thumbprint"
    | "Thumbs Down"
    | "Thumbs Up"
    | "Thumbs Up and Down"
    | "Thumbs Up & Down"
    | "Thumbtack"
    | "Ticket"
    | "Touch Select"
    | "Tractor"
    | "Trophy"
    | "Truck 1"
    | "Truck 2"
    | "Tutorial"
    | "Twitter"
    | "USB"
    | "VR Glasses"
    | "VR Player"
    | "Vault"
    | "Venn Diagram"
    | "Video"
    | "Wall"
    | "Wallet Closed"
    | "Wallet Open"
    | "Website 1"
    | "Website 2"
    | "Website Bar Chart"
    | "Website Line Chart"
    | "Website Map"
    | "WiFi Router"
    | "Wind"
    | "Winner"
    | "Wireless"
    | "Yen"
    | "eLearning"
    | "placeholder"
    | "plus";

export type ButtonIconName = 
    "add-plus"
    | "angle-left-double"
    | "angle-left"
    | "angle-right-double"
    | "angle-right"
    | "angle-up"
    | "angle-down"
    | "arrow-left"
    | "bug"
    | "call"
    | "calendar"
    | "caret-down-filled"
    | "caret-down"
    | "caret-left-filled"
    | "caret-right-filled"
    | "caret-up-filled"
    | "caret-up"
    | "check"
    | "contact"
    | "close"
    | "copy"
    | "download"
    | "edit"
    | "ellipsis"
    | "envelope"
    | "expand"
    | "external"
    | "file-open"
    | "file"
    | "filter"
    | "folder-open"
    | "folder"
    | "heart"
    | "key"
    | "lock-private"
    | "menu"
    | "microphone"
    | "notification"
    | "redo"
    | "refresh"
    | "search"
    | "settings"
    | "share"
    | "status-in-progress"
    | "status-info"
    | "status-negative"
    | "status-pending"
    | "status-positive"
    | "status-stopped"
    | "status-warning"
    | "thumbs-down"
    | "thumbs-down-filled"
    | "thumbs-up"
    | "thumbs-up-filled"
    | "treeview-collapse"
    | "treeview-expand"
    | "undo"
    | "unlocked"
    | "upload"
    | "user-profile"
    | "view-full"
    | "view-horizontal"
    | "view-vertical"
    | "zoom-in"
    | "zoom-out";